apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mda-demo.labels" . | nindent 4 }}
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
  {{- end }}
